
package co.unal.examsUnal.BusinessLogic.ServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExamsByUser", targetNamespace = "http://Service.BusinessLogic.humanResources.unal.co/", wsdlLocation = "http://alejandro:8080/HumanResources/ExamsByUser?wsdl")
public class ExamsByUser_Service
    extends Service
{

    private final static URL EXAMSBYUSER_WSDL_LOCATION;
    private final static WebServiceException EXAMSBYUSER_EXCEPTION;
    private final static QName EXAMSBYUSER_QNAME = new QName("http://Service.BusinessLogic.humanResources.unal.co/", "ExamsByUser");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://alejandro:8080/HumanResources/ExamsByUser?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMSBYUSER_WSDL_LOCATION = url;
        EXAMSBYUSER_EXCEPTION = e;
    }

    public ExamsByUser_Service() {
        super(__getWsdlLocation(), EXAMSBYUSER_QNAME);
    }

    public ExamsByUser_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMSBYUSER_QNAME, features);
    }

    public ExamsByUser_Service(URL wsdlLocation) {
        super(wsdlLocation, EXAMSBYUSER_QNAME);
    }

    public ExamsByUser_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMSBYUSER_QNAME, features);
    }

    public ExamsByUser_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExamsByUser_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExamsByUser
     */
    @WebEndpoint(name = "ExamsByUserPort")
    public ExamsByUser getExamsByUserPort() {
        return super.getPort(new QName("http://Service.BusinessLogic.humanResources.unal.co/", "ExamsByUserPort"), ExamsByUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExamsByUser
     */
    @WebEndpoint(name = "ExamsByUserPort")
    public ExamsByUser getExamsByUserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service.BusinessLogic.humanResources.unal.co/", "ExamsByUserPort"), ExamsByUser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMSBYUSER_EXCEPTION!= null) {
            throw EXAMSBYUSER_EXCEPTION;
        }
        return EXAMSBYUSER_WSDL_LOCATION;
    }

}
