
package co.unal.examsUnal.BusinessLogic.ServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExamsByUser", targetNamespace = "http://Service.BusinessLogic.humanResources.unal.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExamsByUser {


    /**
     * 
     * @return
     *     returns co.unal.examsUnal.BusinessLogic.ServiceClient.UserExams
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExamsRequired", targetNamespace = "http://Service.BusinessLogic.humanResources.unal.co/", className = "co.unal.examsUnal.BusinessLogic.ServiceClient.GetExamsRequired")
    @ResponseWrapper(localName = "getExamsRequiredResponse", targetNamespace = "http://Service.BusinessLogic.humanResources.unal.co/", className = "co.unal.examsUnal.BusinessLogic.ServiceClient.GetExamsRequiredResponse")
    @Action(input = "http://Service.BusinessLogic.humanResources.unal.co/ExamsByUser/getExamsRequiredRequest", output = "http://Service.BusinessLogic.humanResources.unal.co/ExamsByUser/getExamsRequiredResponse")
    public UserExams getExamsRequired();

}
